services:
  node:
    image: iulspop/learn-chinese-node:latest
    ports:
      - "3002:3000"
    environment:
      - PYTHON_API_URL=http://python:5001
    volumes:
      - ./data:/app/data
    depends_on:
      - python
    restart: unless-stopped

  python:
    image: iulspop/learn-chinese-python:latest
    env_file:
      - .env.production
    volumes:
      - ./data:/app/data
      - ./gcp-key.json:/app/gcp-key.json:ro
    restart: unless-stopped
